Test vat interactions
marsfoundation/endgame-testnet-setup pull request #11
Opened 2024-08-30 10:58 UTC by krzkaczor

2024-08-30 15:29 UTC, barrutko approved these changes
We have a convention to leave an empty line at the end of the file and empty line before the end of the contract. As in `script/SetupAll.s.sol`.

Also I know that these are just sanity checks, but I'd also add assertions before executions, so we not only assert the final state, but we actually assert that the execution of a given method altered the state in a way we want.

Other than that LGTM.

2024-08-30 16:33 UTC, hexonaut requested changes

2024-08-30 16:33 UTC, hexonaut commented on test/SetupAllMainnet.t.sol
>          IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
Can use `Ethereum.USDC` from `spark-address-registry`.

2024-09-02 08:35 UTC, barrutko approved these changes

2024-09-02 12:27 UTC, hexonaut approved these changes

2024-09-02 12:34 UTC, merged